### ISSUE TITLE
Posting a new flowsheet entry results in a postgres error

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/Backend-Service#19]
Sample payload being sent `POST` to `/flowsheet`

```{"show_id":8,"artist_name":"Portishead","track_title":"Glory Box","album_title":"Dummy"}```

Results in a `500` error with the following message:

```PostgresError: column "play_freq" does not exist<br>    at ErrorResponse (/app/node_modules/postgres/cjs/src/connection.js:790:26)<br>    at handle (/app/node_modules/postgres/cjs/src/connection.js:476:6)<br>    at Socket.data (/app/node_modules/postgres/cjs/src/connection.js:315:9)<br>    at Socket.emit (node:events:517:28)<br>    at addChunk (node:internal/streams/readable:368:12)<br>    at readableAddChunk (node:internal/streams/readable:341:9)<br>    at Readable.push (node:internal/streams/readable:278:10)<br>    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)```

**Comment by dvdokkum** [comment]
Fixed in #21
